apiVersion: batch/v1
kind: Job
metadata:
  name: populate-vectordb
spec:
  completions: 1 
  activeDeadlineSeconds: 1800
  backoffLimit: 1
  template:   
    metadata:
      name: populate-vectordb
    spec:
      containers:
      - name: populate-vectordb
        image: quay.io/ecosystem-appeng/embeddingjob:0.0.3
        command: ["/usr/bin/bash", "/app/entrypoint.sh"]
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: DB_TYPE
            value: "REDIS"
          - name: REDIS_URL
            value: "redis://redis-stack-server.$(NAMESPACE).svc.cluster.local:6379"
          - name: TRANSFORMERS_CACHE
            value: '/cache/.cache'
          - name: SENTENCE_TRANSFORMERS_HOME
            value: '/cache/.cache'
          - name: DOC_GIT_REPO
            value: https://github.com/RHEcosystemAppEng/llm-on-openshift.git
          - name: DOC_LOCATION
            value: examples/notebooks/langchain/rhods-doc
          - name: TEMP_DIR
            value: '/tmp'
        volumeMounts:
        - mountPath: /cache/
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 2Gi
      restartPolicy: Never
