apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-monitoring
patchesJSON6902:
  - target:
      group: operators.coreos.com
      version: v1
      kind: OperatorGroup
      name: prometheus-og
    patch: |-
      - op: replace
        path: /spec/targetNamespaces/0
        value: llm-monitoring
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: ai-llm-gradio-sm
    patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: rag-llm
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: ai-llm-tgis-sm
    patch: |-
      - op: replace
        path: /spec/namespaceSelector/matchNames/0
        value: rag-llm
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: ai-llm-monitoring-crb
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: llm-monitoring
resources:
  - ../../base/operators.coreos.com/operatorgroups/prometheus
  - ../../base/operators.coreos.com/subscriptions/prometheus
  - ../../base/operators.coreos.com/subscriptions/grafana
  - ../../base/prometheus
  - ../../base/grafana
  - ../../base/grafanadashboard
  - ../../base/servicemonitor
  - ../../base/rbac/clusterrole
  - ../../base/rbac/clusterrolebinding
  - namespaces
