---
global:
  pattern: rag-llm-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
# Possible value for db.type = [REDIS, EDB, ELASTIC]
  db:
    index: docs
    type: EDB
# Add for model ID
  model:
      modelId: ibm-granite/granite-3.1-8b-instruct
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
