apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: frontend
  name: ai-llm-gradio-sm
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - tgis-llm-demo
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [ui-multiprovider-rag-redis,gradio-hftgi-rag-redis-model1,gradio-hftgi-rag-redis-model2]}
