apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: frontend
  name: ai-llm-tgis-sm
spec:
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - tgis-llm-demo
  selector:
    matchExpressions:
      - {key: app.kubernetes.io/instance, operator: In, values: [tgis-server]}
