kind: Deployment
apiVersion: apps/v1
metadata:
  name: gradio-hftgi-rag-redis-model1
  labels:
    app: gradio-hftgi-rag-redis-model1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-hftgi-rag-redis-model1
  template:
    metadata:
      labels:
        app: gradio-hftgi-rag-redis-model1
    spec:
      volumes:
        - name: redis-schema
          configMap:
            name: redis-schema
            items:
              - key: redis_schema.yaml
                path: redis_schema.yaml
            defaultMode: 420
        - name: cache-volume
          emptyDir:
            sizeLimit: 2Gi
      initContainers:
        - name: wait-for-redis
          image: goodsmileduck/redis-cli
          imagePullPolicy: IfNotPresent
          args: [ 'sh', '-c', 'until redis-cli -h my-doc-headless.$(NAMESPACE).svc.cluster.local -p 10225  get hello; do echo "Sleeping a bit"; sleep 1; done; echo "ready!"; ' ]
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: server
          livenessProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 8
            periodSeconds: 100
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: redb-my-doc
                  key: password
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_TITLE
              value: Talk with your documentation
            - name: INFERENCE_SERVER_URL
              value: >-
                http://hf-text-generation-inference-server-model1.$(NAMESPACE).svc.cluster.local:3000
            - name: REDIS_URL
              value: >-
                redis://default:$(DB_PASS)@my-doc-headless.$(NAMESPACE).svc.cluster.local:10225
            - name: REDIS_INDEX
              value: docs
            - name: MAX_NEW_TOKENS
              value: '1024'
            - name: TOP_K
              value: '10'
            - name: TOP_P
              value: '0.95'
            - name: TYPICAL_P
              value: '0.95'
            - name: TEMPERATURE
              value: '0.01'
            - name: REPETITION_PENALTY
              value: '1.03'
            - name: TIMEOUT
              value: '30'
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /queue/status
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 24
          volumeMounts:
            - name: redis-schema
              mountPath: /opt/app-root/src/redis_schema.yaml
              subPath: redis_schema.yaml
            - name: cache-volume
              mountPath: /opt/app-root/src/assets/proposal-docs
          terminationMessagePolicy: File
          image: 'quay.io/ecosystem-appeng/openshift-ai-demo:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
