- name: Generate Machine Set for RAG-LLM Pattern
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ns: imperative
    usable_regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - sa-east-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-north-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
  tasks:
    - name: "[create-gpu-machine-set] Get the infrai-id for the cluster"
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: infrastructure
        name: cluster
      register: infraInfo

    - name: "[create-gpu-machine-set] Get Platform Name"
      ansible.builtin.set_fact:
        cloudProvider: "{{ infraInfo.resources[0].status.platform | lower }}"

    - name: "[create-gpu-machine-set] Set fact Region"
      ansible.builtin.set_fact:
        cloudRegion: "{{ infraInfo.resources[0].status.platformStatus[cloudProvider].region }}"

    - name: "[create-gpu-machine-set] Search for MachineSets"
      kubernetes.core.k8s_info:
        api: machine.openshift.io/v1beta1
        kind: MachineSet
        namespace: openshift-machine-api
      register: machineset

    - name: "[create-gpu-machine-set] Get the availability zone from the first worker MachineSets"
      ansible.builtin.set_fact:
        cloudAvailabilityZone: "{{ item.spec.template.spec.providerSpec.value.placement.availabilityZone }}"
      with_items:
        - "{{ machineset.resources[0] }}"

    - name: "[create-gpu-machine-set] Search for worker MachineSets"
      kubernetes.core.k8s_info:
        api: machine.openshift.io/v1beta1
        kind: Machine
        namespace: openshift-machine-api
        label_selectors:
          - "machine.openshift.io/cluster-api-machine-type=worker"
      register: machines

    - name: "[create-gpu-machine-set] Setting facts to be used in MachineSet template"
      ansible.builtin.set_fact:
        clusterId: "{{ infraInfo.resources[0].status.infrastructureName }}"
        instanceAmi: "{{ machines.resources[0].spec.providerSpec.value.ami.id }}"
        cacheable: no
        securityGroups: "{{ machines.resources[0].spec.providerSpec.value.securityGroups }}"
        subnets: "{{ machines.resources[0].spec.providerSpec.value.subnet }}"
        tags: "{{ machines.resources[0].spec.providerSpec.value.tags }}"

    - name: "[create-gpu-machine-set] Generate machineset"
      ansible.builtin.template:
        src: templates/gpu-machine-sets.j2
        dest: /tmp/gpu-machineset.yaml

    - name: "[create-gpu-machine-set] Apply machineset to cluster {{ clusterId }}"
      kubernetes.core.k8s:
        state: present
        src: /tmp/gpu-machineset.yaml
      when: cloudRegion in usable_regions
