apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: rag-llm
patchesJSON6902:
  - patch: |-
      - op: replace
        path: /spec/targetNamespaces/0
        value: rag-llm
    target:
      group: operators.coreos.com
      kind: OperatorGroup
      name: redis
      version: v1
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: 'system:openshift:scc:redis-enterprise-scc-v2'
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: rag-llm
resources:
  - ../../base/security
  - ../../base/operators.coreos.com/operatorgroups/redis
  - ../../base/operators.coreos.com/subscriptions/redis
  - ../../base/redisenterprises
  - ../../base/redisenterprisedatabases
  - ../../base/deployments
  - ../../base/services
  - ../../base/configmaps
  - ../../base/persistentvolumeclaims
  - ../../base/routes
  - ../../base/jobs
  - namespaces
secretGenerator:
  - literals:
      - token=PLACEHOLDER
    name: huggingface-hub-token
